### ISSUE TITLE
Map doesn't pan at all

### ISSUE THREAD

**Issue by hibyguy** [humphd/bridge-troll#10]
There's an issue where I can't double click or hold click to pan the map viewer! 
Win 10 64bit regular installation of application

**Comment by humphd** [comment]
See https://github.com/humphd/bridge-troll/blob/master/src/map.js#L36-L45 which is what is doing this.  We could write some "debug" type code to allow you to override this when testing?

**Comment by hibyguy** [comment]
Yup yup, this worked. 
Thanks

**Comment by humphd** [comment]
I landed this PR.
